# Learning source:
# https://opensource.com/article/18/3/manage-workstation-ansible

- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - mc
      - tmux

